### ISSUE TITLE
The jump button is not styled?

### ISSUE THREAD

**Issue by YhyaGithub** [YhyaGithub/JumpLand#1]
When i press jump there is no any hover or something and nothin happens when i press it.
Please fix it.

**Comment by Somespi** [comment]
I'll consider doing it

**Comment by YhyaGithub** [comment]
> I'll consider doing it

I started working at this in 'https://github.com/YhyaGithub/JumpLand/commit/85b67e77d2814b42287f77f3eea34635b973a0a2' but there is no gravity.

**Comment by YhyaGithub** [comment]
You can work at the styling

**Comment by Somespi** [comment]
Done
